export const LOADING_QUESTIONS = 'LOADING_QUESTIONS';

export const START_INTERVIEW = 'START_INTERVIEW';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';

export const POST_QUESTION_ANSWER = 'POST_QUESTION_ANSWER';
export const POST_USER="POST_USER"

export const LOADING_FEEDBACK = "LOADING_FEEDBACK";
export const CLEAR_FEEDBACK = "CLEAR_FEEDBACK";

